version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8
    networks:
      env-hdfs-network:
        ipv4_address: 172.16.0.2
    ports:
      - 9000:9000
      - 9870:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    networks:
      env-hdfs-network:
        ipv4_address: 172.16.0.10
    ports:
      - 9864:9864
      - 9866:9866
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

networks:
  env-hdfs-network:
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  hadoop_namenode:
  hadoop_datanode:
